version: '3.8'

services:
  postgres_db:
    image: 'postgres:14.1-alpine'
    restart: 'always'
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT}:5432'
